name = "leverage-ai-cms"
main = "src/index.js"
compatibility_date = "2025-07-07"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "leverage-ai-cms-prod"

# CMS requires multiple bindings
[[env.production.kv_namespaces]]
binding = "CONTENT"
id = "8aa7ae21fcd6492a9c60a238d5d83e54"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "b43c3075153246de9abadfa1b7a53125"

# CACHE KV namespace - ✅ NOW CONFIGURED!
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "5aec1ca2eef74413b44865535e43aa81"

[[env.production.vectorize]]
binding = "SEARCH_INDEX"
index_name = "cms-search"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cms-production"
database_id = "34c83d16-680c-4656-b2cd-be00c60c1db2"

[env.production.ai]
binding = "AI"

[env.production.vars]
ENVIRONMENT = "production"
CMS_VERSION = "1.0.0"
LOG_LEVEL = "info"
CORS_ORIGIN = "https://your-cms.pages.dev"

# Development environment
[env.development]
name = "leverage-ai-cms-dev"

[[env.development.kv_namespaces]]
binding = "CONTENT"
id = "8aa7ae21fcd6492a9c60a238d5d83e54"

[[env.development.kv_namespaces]]
binding = "USERS"
id = "b43c3075153246de9abadfa1b7a53125"

# CACHE KV namespace - TODO: Create separate dev cache namespace
# [[env.development.kv_namespaces]]
# binding = "CACHE"
# id = "5aec1ca2eef74413b44865535e43aa81"

[[env.development.vectorize]]
binding = "SEARCH_INDEX"
index_name = "cms-search-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "cms-production-dev"
database_id = "22b8a8f7-d061-43ec-965d-c5369ce81c44"

[env.development.ai]
binding = "AI"

[env.development.vars]
ENVIRONMENT = "development"
CMS_VERSION = "1.0.0-dev"
LOG_LEVEL = "debug"
CORS_ORIGIN = "http://localhost:3000"

# Routes for custom domain (update when ready)
# [[env.production.routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"