name = "leverage-ai-cms"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "leverage-ai-cms-prod"

# Enhanced for CMS workloads
[limits]
cpu_ms = 50000

# CMS requires multiple bindings
[[env.production.kv_namespaces]]
binding = "CONTENT"
id = "4c59b1de85d14cceaedb3e035f14ae44"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "YOUR_USERS_KV_ID"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "YOUR_CACHE_KV_ID"

[[env.production.vectorize]]
binding = "SEARCH_INDEX"
index_name = "cms-search"

[[env.production.d1_databases]]
binding = "CMS_DB"
database_name = "cms-production"
database_id = "YOUR_D1_DATABASE_ID"

[env.production.ai]
binding = "AI"

[env.production.vars]
ENVIRONMENT = "production"
CMS_VERSION = "1.0.0"
LOG_LEVEL = "info"
CORS_ORIGIN = "https://your-cms.pages.dev"

# Development environment
[env.development]
name = "leverage-ai-cms-dev"

[[env.development.kv_namespaces]]
binding = "CONTENT"
id = "4c59b1de85d14cceaedb3e035f14ae44"

[[env.development.kv_namespaces]]
binding = "USERS"
id = "YOUR_DEV_USERS_KV_ID"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "YOUR_DEV_CACHE_KV_ID"

[[env.development.vectorize]]
binding = "SEARCH_INDEX"
index_name = "cms-search-dev"

[env.development.ai]
binding = "AI"

[env.development.vars]
ENVIRONMENT = "development"
CMS_VERSION = "1.0.0-dev"
LOG_LEVEL = "debug"
CORS_ORIGIN = "http://localhost:3000"

# Routes for custom domain (update when ready)
# [[env.production.routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"